version: '2'
services:
    think_swoole:
        build: .
        container_name: think_swoole
        volumes:
            - ./think_swoole/:/data/www/
            - ./conf/conf.d/:/usr/local/tengine/conf/conf.d/
            - ./conf/nginx.conf:/usr/local/tengine/conf/nginx.conf
        ports:
            - "85:80"
            - "443:443"
            - "9503:9501"
            - "9504:9502"